package com.furb.mancala.web.client;

import com.furb.mancala.web.MancalaWebApplication;
import com.furb.mancala.web.model.MancalaJogo;
import com.furb.mancala.web.model.MancalaBuraco;
import org.assertj.core.api.BDDAssertions;
import org.junit.Test;
import org.junit.runner.RunWith;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.json.AutoConfigureJson;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.stubrunner.spring.AutoConfigureStubRunner;
import org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit4.SpringRunner;
import java.util.Arrays;
import java.util.List;

/*
    This class performs Contract based Testing for Mancala-api service based on the Stub generated by service itself
 */

@AutoConfigureStubRunner (
        ids = "com.furb.mancalagame:mancala-api:+:8080",
        stubsMode = StubRunnerProperties.StubsMode.LOCAL)
@AutoConfigureJson
@SpringBootTest (classes = MancalaWebApplication.class)
@RunWith(SpringRunner.class)
@DirtiesContext
public class CDCApplicationTests {

    @Autowired
    private MancalaClient mancalaClient;

    @Test
    public void testManacalaCreation () throws Exception {

    	MancalaJogo mancalaJogo = mancalaClient.iniciaNovoJogoMancala();

        List<MancalaBuraco> MancalaBuracos = Arrays.asList(
                new MancalaBuraco(1 , 6),
                new MancalaBuraco(2 , 6),
                new MancalaBuraco(3 , 6),
                new MancalaBuraco(4 , 6),
                new MancalaBuraco(5 , 6),
                new MancalaBuraco(6 , 6),
                new MancalaBuraco(7 , 0),
                new MancalaBuraco(8 , 6),
                new MancalaBuraco(9 , 6),
                new MancalaBuraco(10 , 6),
                new MancalaBuraco(11 , 6),
                new MancalaBuraco(12 , 6),
                new MancalaBuraco(13 , 6),
                new MancalaBuraco(14 , 0));

        BDDAssertions.then(mancalaJogo.getPartidaJogador()).isNull();
        BDDAssertions.then(mancalaJogo.getBuracos()).isEqualTo(MancalaBuracos);
        BDDAssertions.then(mancalaJogo.getPedrasLadoEsquerdo()).isEqualTo(0);
        BDDAssertions.then(mancalaJogo.getPedrasLadoDireito()).isEqualTo(0);
    }

    /*
      We first need to run the Mancala Game creation test and use the game id generated to sow the game
   */
    @Test
    public void testManacalaSowingPitIndex2 () throws Exception {

    	MancalaJogo mancalaJogo = mancalaClient.iniciaNovoJogoMancala();

        List<MancalaBuraco> MancalaBuracos = Arrays.asList(
                new MancalaBuraco(1 , 6),
                new MancalaBuraco(2 , 6),
                new MancalaBuraco(3 , 6),
                new MancalaBuraco(4 , 6),
                new MancalaBuraco(5 , 6),
                new MancalaBuraco(6 , 6),
                new MancalaBuraco(7 , 0),
                new MancalaBuraco(8 , 6),
                new MancalaBuraco(9 , 6),
                new MancalaBuraco(10 , 6),
                new MancalaBuraco(11 , 6),
                new MancalaBuraco(12 , 6),
                new MancalaBuraco(13 , 6),
                new MancalaBuraco(14 , 0));

        BDDAssertions.then(mancalaJogo.getPartidaJogador()).isNull();
        BDDAssertions.then(mancalaJogo.getBuracos()).isEqualTo(MancalaBuracos);
        BDDAssertions.then(mancalaJogo.getPedrasLadoEsquerdo()).isEqualTo(0);
        BDDAssertions.then(mancalaJogo.getPedrasLadoDireito()).isEqualTo(0);

        // 2. Run the Mancala Sow test for pit 2

        MancalaJogo kalahaGameAfterSowingPit2 = mancalaClient.semeaJogoMancala(mancalaJogo.getId(), 2);

        System.out.println(kalahaGameAfterSowingPit2);

        List<MancalaBuraco> novoMancalaBuracos = Arrays.asList(
                new MancalaBuraco(1 , 6),
                new MancalaBuraco(2 , 0),
                new MancalaBuraco(3 , 7),
                new MancalaBuraco(4 , 7),
                new MancalaBuraco(5 , 7),
                new MancalaBuraco(6 , 7),
                new MancalaBuraco(7 , 1),
                new MancalaBuraco(8 , 7),
                new MancalaBuraco(9 , 6),
                new MancalaBuraco(10 , 6),
                new MancalaBuraco(11 , 6),
                new MancalaBuraco(12 , 6),
                new MancalaBuraco(13 , 6),
                new MancalaBuraco(14 , 0));

        BDDAssertions.then(kalahaGameAfterSowingPit2.getPartidaJogador()).isEqualTo("PlayerB");
        BDDAssertions.then(kalahaGameAfterSowingPit2.getBuracos()).isEqualTo(novoMancalaBuracos);
        BDDAssertions.then(kalahaGameAfterSowingPit2.getPedrasLadoEsquerdo()).isEqualTo(0);
        BDDAssertions.then(kalahaGameAfterSowingPit2.getPedrasLadoDireito()).isEqualTo(1);
    }
}
